name: Ricardo Balk
author: Ricardo Balk
author_first_name: Ricardo
author_last_name: Balk
description: Blog
avatar: img/avatar.png

social:
  behance: ricardobalk
  disqus: ricardobalk
  facebook: ellipticcurv3
  github: ellipticcurv3
  instagram: ellipticcurv3
  keybase: ellipticcurv3
  linkedin: ricardobalk
  stackoverflow: ellipticcurv3
  twitter: ellipticcurv3
  youtube: # channel/<your_long_string> or user/<user-name>

collections:
  portfolio:
    output: true
    permalink: /:collection/:name

disqus: ricardobalk # Disqus shortname (not the username)
google_analytics:   # UA-16034023-12

url: "https://www.ricardobalk.nl" # Used for Sitemap.xml and your RSS feed
baseurl: ""
onion: "http://3rfoq3ia75hnxgpmtwyeyvbjbhym354tcy4ox2jaqjqhtcmd4i2mt2id.onion" # If available via Tor

source: src
destination: dist
permalink: /blog/:categories/:title/

kramdown:
  input: GFM # Use GitHub flavored markdown, including triple backtick fenced code blocks
  syntax_highlighter: rouge # Jekyll 3 and GitHub Pages only support rouge
  syntax_highlighter_opts:
    css_class: 'highlight' # Use existing pygments syntax highlighting css

darkmode: false

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - _posts/TEMPLATE.md
  - _portfolio/TEMPLATE.md
  - node_modules/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/